#!/bin/sh
#this file takes the large number of files that are generated by running the pipeline and organizes them neatly. 
mkdir models
mv fullModel models
mv fold1Model models
mv fold2Model models
mv fold3Model models
mv fold4Model models
mkdir svmpredictions
mv fullOutput svmpredictions
mv fold1HeldOutOutput svmpredictions
mv fold2HeldOutOutput svmpredictions
mv fold3HeldOutOutput svmpredictions
mv fold4HeldOutOutput svmpredictions
mv fold1TrainingOutput svmpredictions
mv fold2TrainingOutput svmpredictions
mv fold3TrainingOutput svmpredictions
mv fold4TrainingOutput svmpredictions
mkdir graphingdata
mv fullData graphingdata
mv fold1HeldOutData graphingdata
mv fold2HeldOutData graphingdata
mv fold3HeldOutData graphingdata
mv fold4HeldOutData graphingdata
mv fold1TrainingData graphingdata
mv fold2TrainingData graphingdata
mv fold3TrainingData graphingdata
mv fold4TrainingData graphingdata
mkdir svmtestfiles
mv full svmtestfiles
mv fold1HeldOut svmtestfiles
mv fold2HeldOut svmtestfiles
mv fold3HeldOut svmtestfiles
mv fold4HeldOut svmtestfiles
mkdir svmtrainingfiles
mv fold1 svmtrainingfiles
mv fold2 svmtrainingfiles
mv fold3 svmtrainingfiles
mv fold4 svmtrainingfiles
cp svmtestfiles/full svmtrainingfiles
mkdir pipelineOutput
mv graphingdata pipelineOutput
mv models pipelineOutput
mv svmpredictions pipelineOutput
mv svmtestfiles pipelineOutput
mv svmtrainingfiles pipelineOutput
mv graphs.png pipelineOutput
