python create_mapper.py -a /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/assemblies/PGAs/anterior_nares -r /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/reads -g /n/huttenhower_lab_nobackup/downloads/HMP/HMGI/anterior_nares -n SKIN -o input/mapper_anterior_nares.txt
python create_mapper.py -a /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/assemblies/PGAs/posterior_fornix -r /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/reads -g /n/huttenhower_lab_nobackup/downloads/HMP/HMGI/posterior_fornix -n VAGINA -o input/mapper_posterior_fornix.txt
python create_mapper.py -a /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/assemblies/PGAs/stool -r /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/reads -g /n/huttenhower_lab_nobackup/downloads/HMP/HMGI/stool -n GUT -o input/mapper_stool.txt
python create_mapper.py -a /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/assemblies/PGAs/buccal_mucosa -r /n/huttenhower_lab_nobackup/downloads/HMP/HMASM/reads -g /n/huttenhower_lab_nobackup/downloads/HMP/HMGI/buccal_mucosa -n ORAL -o input/mapper_buccal_mucosa.txt


